site_name: Kransy
site_url: https://kransy.github.io/
site_author: Kransy
site_description: "Blog relatif à mon chemin dans la cybersécurité"
copyright: "Cinder is licensed under the <a href='https://github.com/chrissimpkins/cinder/blob/master/LICENSE.md'>MIT license</a>"

theme:
  name: null
  custom_dir: cinder
  colorscheme: github
  highlightjs: true

nav:
  - Home: index.md
  - About: specimen.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
